### ISSUE TITLE
其它用户登录后，右上角无法编辑资料

### ISSUE THREAD

**Issue by zgx030030** [fangzesheng/f-admin#8]
添加用户并使用新用户登录后台，点击右上角编辑资料和密码，提示没有权限。权限设置里也没有此权限的设置

**Comment by fangzesheng** [comment]
> 添加用户并使用新用户登录后台，点击右上角编辑资料和密码，提示没有权限。权限设置里也没有此权限的设置

这个需要把编辑资料的权限通过权限管理添加进去，然后在把这个权限赋给这个用于的角色就行了，不过我前端还是要改下
